# -*- coding: utf-8 -*-
"""file.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uE9198vVonAJQjdVSBKlrkfn7ogw9B5w
"""



import streamlit as st
import pandas as pd
import joblib
import matplotlib.pyplot as plt

st.set_page_config(layout="wide")
st.title("Apple Stock Price Prediction using ARIMA")

# Load the pre-trained ARIMA model
# Make sure 'arima_model.joblib' is in the same directory as this Streamlit app
try:
    model = joblib.load('arima_model.joblib')
    st.success("ARIMA model loaded successfully!")

    train_data = None
    try:
        # First, try to access model.data.endog as is common for statsmodels fitted results
        raw_endog_data = model.data.endog

        # Ensure it's a pandas Series
        if not isinstance(raw_endog_data, pd.Series):
            train_data = pd.Series(raw_endog_data)
            st.info("Converted raw endogenous data to pandas Series.")
        else:
            train_data = raw_endog_data

        # Ensure the index is datetime
        if not isinstance(train_data.index, pd.DatetimeIndex):
            train_data.index = pd.to_datetime(train_data.index)

    except AttributeError:
        # If model.data or model.data.endog is not found, try alternative (e.g., direct model.endog if it's an unfitted model)
        st.warning("Could not find 'model.data.endog'. Attempting to find 'model.endog' directly.")
        try:
            raw_endog_data = model.endog
            if not isinstance(raw_endog_data, pd.Series):
                train_data = pd.Series(raw_endog_data)
                st.info("Converted raw endogenous data to pandas Series from 'model.endog'.")
            else:
                train_data = raw_endog_data

            if not isinstance(train_data.index, pd.DatetimeIndex):
                train_data.index = pd.to_datetime(train_data.index)
        except AttributeError:
            st.error("Neither 'model.data.endog' nor 'model.endog' could be found. Model object structure is unexpected.")
            raise ValueError("Training data could not be extracted from the model.")
        except Exception as e:
            st.error(f"An error occurred while processing 'model.endog': {e}")
            raise ValueError("Training data could not be extracted or processed from 'model.endog'.")
    except Exception as e:
        st.error(f"An unexpected error occurred during initial data extraction: {e}")
        raise # Re-raise other exceptions

    # Final check after all attempts
    if train_data is None or train_data.empty or not isinstance(train_data.index, pd.DatetimeIndex):
        st.error("Fatal Error: Training data could not be extracted, converted to a pandas Series, or given a DatetimeIndex. Cannot proceed with time series forecasting.")
        raise ValueError("Training data extraction or formatting failed critically.")

except FileNotFoundError:
    st.error("Error: 'arima_model.joblib' not found. Please ensure the model file is in the correct directory.")
    raise FileNotFoundError("ARIMA model file not found.")
except Exception as e:
    st.error(f"An error occurred while loading or processing the model: {e}")
    raise # Re-raise the caught exception

# Get the last date from the training data for forecasting context
# We now assume train_data is correctly extracted from the model
last_train_date = train_data.index[-1]
last_train_value = train_data.iloc[-1]

st.write(f"Model trained up to: {last_train_date.strftime('%Y-%m-%d')}")
st.write(f"Last observed closing price (from training data): ${last_train_value:.2f}")

st.sidebar.header("Prediction Settings")
num_days = st.sidebar.slider("Number of days to forecast:", min_value=1, max_value=90, value=30)

if st.sidebar.button("Generate Forecast"):
    st.subheader(f"Forecasting Apple Stock Price for the next {num_days} days")

    # Generate forecast
    # The forecast method of a fitted ARIMA model needs the `steps` parameter
    # and will continue from the end of the data it was fitted on.
    try:
        # The start and end parameters for predict method are usually relative to the training data length.
        forecast = model.predict(start=len(train_data), end=len(train_data) + num_days - 1)

        # Create a date range for the forecast
        # 'B' for business day frequency
        forecast_dates = pd.date_range(start=last_train_date + pd.Timedelta(days=1), periods=num_days, freq='B')

        forecast_df = pd.DataFrame({'Date': forecast_dates, 'Predicted Close': forecast.values})
        forecast_df.set_index('Date', inplace=True)

        st.write("### Predicted Prices:")
        st.dataframe(forecast_df)

        # Plotting the forecast
        st.write("### Forecast Visualization:")
        fig, ax = plt.subplots(figsize=(12, 6))
        ax.plot(train_data.index, train_data, label='Historical Training Data', color='blue')
        # Check if test_data exists and plot it if available
        if 'test_data' in globals() and not test_data.empty:
            ax.plot(test_data.index, test_data, label='Actual Test Data', color='orange')
        ax.plot(forecast_df.index, forecast_df['Predicted Close'], label='Forecasted Prices', color='red', linestyle='--')
        ax.set_title('Apple Stock Price Forecast')
        ax.set_xlabel('Date')
        ax.set_ylabel('Close Price')
        ax.legend()
        ax.grid(True)
        st.pyplot(fig)

    except Exception as e:
        st.error(f"An error occurred during forecasting: {e}")

st.markdown("---")
st.write("This is a demonstration of an ARIMA model for stock price prediction.")
st.write("Disclaimer: Stock market predictions are inherently uncertain. This tool is for educational purposes only and should not be considered financial advice.")



import pandas as pd
import numpy as np
import joblib
from statsmodels.tsa.arima.model import ARIMA

# --- 1. Generate some dummy time series data for demonstration ---
# In a real scenario, you would load your actual Apple stock data here.
np.random.seed(42)
dates = pd.date_range(start='2020-01-01', periods=100, freq='D')
data = np.cumsum(np.random.randn(100)) + 50 # A simple random walk
train_data_example = pd.Series(data, index=dates)

print("Sample training data head:")
print(train_data_example.head())
print("Sample training data tail:")
print(train_data_example.tail())

# --- 2. Fit an ARIMA model to the data ---
# Using a simple (1,1,1) ARIMA model as an example.
# You should determine appropriate p, d, q values based on your data analysis.
print("\nFitting ARIMA model...")
model_instance = ARIMA(train_data_example, order=(1, 1, 1))
model_fit = model_instance.fit()

print("ARIMA model fitted successfully!")
print(model_fit.summary())

# --- 3. Save the *fitted results* object ---
# It's crucial to save the 'model_fit' object, not 'model_instance'.
joblib.dump(model_fit, 'arima_model.joblib')
print("\nFitted ARIMA model saved as 'arima_model.joblib'.")
print("You can now run your Streamlit app with this updated model file.")

"""#### **Important:**

1.  **Run the cell above first** to create the `arima_model.joblib` file with a *fitted* model.
2.  **Then, re-run your Streamlit application cell (`e5_YtqCaZf2h`)** to load this newly created `arima_model.joblib`.

The `arima_model.joblib` file should now contain a fitted ARIMA model object, which includes the estimated parameters, allowing the `predict` method to be called without needing to pass `params` explicitly. If you use your own `arima_model.joblib` file, make sure it was generated by saving the `.fit()` result, not just the ARIMA model definition.
"""